version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agenda_db
    tty: true
    networks:
      - backend_network
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3333:3333"
    restart: always
    tty: true
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; yarn && yarn start"
    networks:
      - backend_network
    volumes:
      - ./server 
    depends_on:
      - db
networks:
  backend_network:
volumes:
  database: