version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    environment:
      - POSTGRES_USER-postgres
      - POSTGRES_PASSWORD-postgres
      - POSTGRES_DB=agenda_db
    networks:
      - backend_network
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

networks:
  backend_network:

volumes:
  database: